## A simple logistic reg model with only one predictor variable

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("C:/Users/hp/Classification preprocessed data Python.csv", header = 0)

In [3]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

## Logistic reg using sklearn lib

 1. create classification object
 2. fit object using x and y var
 3. predict our y var using the trained classification model
 

In [4]:
#selected only one independent var(price) and one dependent var(sold)
#in sklearn your independent var should be a 2d array
X = df[["price"]]

In [5]:
y = df["Sold"]

In [6]:
X.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [8]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
clf_lrs = LogisticRegression()

In [11]:
clf_lrs.fit(X,y)

LogisticRegression()

In [14]:
clf_lrs.coef_
#beta1

array([[-0.03571865]])

In [15]:
clf_lrs.intercept_
#beta0

array([0.61477516])

## Using stats model to create a logistic reg model

In [17]:
import statsmodels.api as sn

In [18]:
X_cons = sn.add_constant(X)

In [19]:
X_cons.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [20]:
import statsmodels.discrete.discrete_model as sm

In [21]:
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [22]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Mon, 22 May 2023   Pseudo R-squ.:                 0.01788
Time:                        00:01:57   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

## logistic reg with multiple predictor var

In [23]:
X = df.loc[:, df.columns != "Sold"]

In [25]:
y = df["Sold"]

In [26]:
clf_lr = LogisticRegression()
clf_lr.fit(X,y)

c:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
clf_lr.coef_

array([[-0.24634528, -0.01729821, -0.11019376,  0.86253055, -0.00599817,
         0.22821832, -0.21020198,  0.18008032, -0.09088975, -0.00705221,
        -0.00499207, -0.32612067, -0.10520968, -0.09485992, -0.01512194,
         0.20178319]])

In [28]:
clf_lr.intercept_

array([0.01670923])

## with statsmodel

In [29]:
X_cons = sn.add_constant(X)

In [30]:
logit = sm.Logit(y, X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [31]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Mon, 22 May 2023   Pseudo R-squ.:                  0.1924
Time:                        00:36:16   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""